#!/bin/sh

# g15lcd init script
#
# Copyright 2006-2011 Chris Olstrom
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

N=/etc/init.d/g15lcd

set -e

case "$1" in
	start)
		echo "Starting g15lcd..." >&2
		if [ -p /var/run/g15lcd ]; then
			echo "g15lcd already started." >&2
			exit 1
		fi
		mknod /var/run/g15lcd p
		chgrp g15lcd /var/run/g15lcd
		chmod g+w /var/run/g15lcd
		/usr/bin/g15lcd /var/run/g15lcd > /dev/null &
		echo "g15lcd started." >&2
	;;
	restart)
		$N stop
		$N start
	;;
	stop)
		echo "Stopping g15lcd..." >&2
		if [ -p /var/run/g15lcd ]; then
			rm -f /var/run/g15lcd
			killall /usr/bin/g15lcd
		else
			echo "g15lcd not started." >&2
			exit 1
		fi
		echo "g15lcd stopped." >&2
	;;
	reload|force-reload)
	;;
	*)
		echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
		exit 1
	;;
esac

exit 0
